window.translations = {
  en: {
    title: "KrishiGuru",
    subtitle: "Intelligent Farmer Dashboard",
    soilAnalyzer: "Soil Health Analyzer",
    nitrogen: "Nitrogen (N)",
    phosphorus: "Phosphorus (P)",
    potassium: "Potassium (K)",
    phLevel: "Soil pH Level",
    moisture: "Soil Moisture",
    soilType: "Soil Type",
    location: "Agricultural Region",
    sand: "Sandy",
    clay: "Clayey",
    loam: "Loamy",
    silt: "Silty",
    peat: "Peaty",
    chalk: "Chalky",
    analyzeBtn: "Analyze Soil & Fetch Climate",
    climateCenter: "Climate & Weather Intelligence",
    temperature: "Temperature",
    humidity: "Humidity",
    windSpeed: "Wind Speed",
    rainChance: "Precipitation Chance",
    currentConditions: "Current Conditions",
    weeklyForecast: "7-Day Agronomic Forecast",
    recommendations: "Profit-Maximized Crop Recommendations",
    cropName: "Crop Name",
    suitability: "Suitability Score",
    marketPrice: "Current Market Price",
    expectedProfit: "Projected Profit",
    growthPeriod: "Growth Duration",
    profitTip: "Profit maximized using real-time local mandi price margins.",
    assistantTitle: "Krishi Sahayak (Speech Assistant)",
    assistantGreeting: "Hello! I am Krishi Sahayak. Tap the microphone to speak, or type your query. I can help you improve soil quality, manage pests, check market rates, or schedule irrigation.",
    placeholder: "Ask me anything about crops, pests, soil, or weather...",
    speechActive: "Listening to your voice...",
    speechInactive: "Tap mic to speak",
    btnSend: "Ask",
    irrigationPestScheduler: "Smart Irrigation & Pest Alert Registry",
    nextIrrigation: "Next Scheduled Irrigation",
    pestControl: "Pest Management Advisor",
    selectCrop: "Select Your Crop",
    selectSymptoms: "Select Visual Symptoms",
    recommendTreatment: "Diagnose & Find Treatment",
    pestDiagnosis: "Diagnosis Result",
    recommendedPesticide: "Recommended Pesticide / Treatment",
    safetyInstruction: "Safety Instructions",
    addReminder: "Schedule Spray Reminder",
    days: "days",
    hours: "hours",
    alertRain: "Irrigation Suspended: Heavy rain forecasted!",
    alertIrrigate: "Irrigation Required: Soil moisture is critically low.",
    alertNormal: "Moisture levels stable. Next watering in 18 hours.",
    mandiUnit: "/ quintal",
    currency: "₹"
  },
  hi: {
    title: "कृषिगुरू",
    subtitle: "बुद्धिमान किसान डैशबोर्ड",
    soilAnalyzer: "मिट्टी स्वास्थ्य विश्लेषक",
    nitrogen: "नाइट्रोजन (N)",
    phosphorus: "फास्फोरस (P)",
    potassium: "पोटेशियम (K)",
    phLevel: "मिट्टी का पीएच (pH) स्तर",
    moisture: "मिट्टी की नमी",
    soilType: "मिट्टी का प्रकार",
    location: "कृषि क्षेत्र",
    sand: "बलुई",
    clay: "चिकनी मिट्टी",
    loam: "दोमट मिट्टी",
    silt: "सिल्टी (गाद)",
    peat: "पीटयुक्त",
    chalk: "चाकयुक्त",
    analyzeBtn: "मिट्टी का विश्लेषण करें और मौसम जानें",
    climateCenter: "जलवायु और मौसम बुद्धिमत्ता",
    temperature: "तापमान",
    humidity: "आर्द्रता (नमी)",
    windSpeed: "हवा की गति",
    rainChance: "बारिश की संभावना",
    currentConditions: "वर्तमान स्थिति",
    weeklyForecast: "7-दिवसीय कृषि पूर्वानुमान",
    recommendations: "अधिकतम लाभ वाली फसल सिफारिशें",
    cropName: "फसल का नाम",
    suitability: "उपयुक्तता स्कोर",
    marketPrice: "वर्तमान बाजार मूल्य",
    expectedProfit: "अनुमानित लाभ",
    growthPeriod: "फसल अवधि",
    profitTip: "स्थानीय मंडी मूल्य मार्जिन का उपयोग करके लाभ को अधिकतम किया गया है।",
    assistantTitle: "कृषि सहायक (आवाज सहायक)",
    assistantGreeting: "नमस्कार! मैं आपका कृषि सहायक हूँ। बात करने के लिए माइक दबाएं, या अपना प्रश्न लिखें। मैं मिट्टी सुधार, कीट प्रबंधन, मंडी भाव या सिंचाई योजना में सहायता कर सकता हूँ।",
    placeholder: "फसलों, कीटों, मिट्टी या मौसम के बारे में कुछ भी पूछें...",
    speechActive: "आपकी आवाज़ सुनी जा रही है...",
    speechInactive: "बोलने के लिए माइक दबाएं",
    btnSend: "पूछें",
    irrigationPestScheduler: "स्मार्ट सिंचाई और कीट चेतावनी अनुसूची",
    nextIrrigation: "अगली अनुसूचित सिंचाई",
    pestControl: "कीट प्रबंधन सलाहकार",
    selectCrop: "फसल चुनें",
    selectSymptoms: "लक्षण चुनें",
    recommendTreatment: "निदान और उपचार खोजें",
    pestDiagnosis: "निदान का परिणाम",
    recommendedPesticide: "अनुशंसित कीटनाशक / उपचार",
    safetyInstruction: "सुरक्षा निर्देश",
    addReminder: "छिड़काव अनुसूची अनुस्मारक जोड़ें",
    days: "दिन",
    hours: "घंटे",
    alertRain: "सिंचाई स्थगित: भारी बारिश का पूर्वानुमान है!",
    alertIrrigate: "सिंचाई आवश्यक है: मिट्टी की नमी बेहद कम है।",
    alertNormal: "नमी का स्तर स्थिर है। अगली सिंचाई 18 घंटे में।",
    mandiUnit: "/ क्विंटल",
    currency: "₹"
  },
  ta: {
    title: "கிருஷிகுரு",
    subtitle: "அறிவுசார் உழவர் தகவல் பலகை",
    soilAnalyzer: "மண் வளம் பகுப்பாய்வி",
    nitrogen: "நைட்ரஜன் (N)",
    phosphorus: "பாஸ்பரஸ் (P)",
    potassium: "பொட்டாசியம் (K)",
    phLevel: "மண் pH அளவு",
    moisture: "மண் ஈப்பப்பதம்",
    soilType: "மண் வகை",
    location: "வேளாண் மண்டலம்",
    sand: "மணல் பாங்கான",
    clay: "களிமண்",
    loam: "வண்டல் மண்",
    silt: "படிவு மண்",
    peat: "கரிம மண்",
    chalk: "சுண்ணாம்பு மண்",
    analyzeBtn: "மண்ணை பகுப்பாய்வு செய்து வானிலை பெறுக",
    climateCenter: "காலநிலை மற்றும் வானிலை தகவல்கள்",
    temperature: "வெப்பநிலை",
    humidity: "ஈரப்பதம்",
    windSpeed: "காற்றின் வேகம்",
    rainChance: "மழை வாய்ப்பு",
    currentConditions: "தற்போதைய நிலை",
    weeklyForecast: "7-நாள் வேளாண் கால நிலை",
    recommendations: "அதிக லாபம் தரும் பயிர் பரிந்துரைகள்",
    cropName: "பயிர் பெயர்",
    suitability: "பொருத்தமான மதிப்பெண்",
    marketPrice: "தற்போதைய சந்தை விலை",
    expectedProfit: "எதிர்பார்க்கும் லாபம்",
    growthPeriod: "வளர்ச்சி காலம்",
    profitTip: "உள்ளூர் மண்டி சந்தை விலை அடிப்படையில் லாபம் கணக்கிடப்பட்டுள்ளது.",
    assistantTitle: "கிருஷி सहायक (குரல் உதவியாளர்)",
    assistantGreeting: "வணக்கம்! நான் உங்கள் கிருஷி உதவியாளர். பேச மைக் ஐகானைத் தட்டவும் அல்லது உங்கள் கேள்வியைத் தட்டச்சு செய்யவும். மண் வளம், பூச்சி மேலாண்மை, சந்தை விலை அல்லது நீர் பாசனம் பற்றி நான் உதவுவேன்.",
    placeholder: "பயிர்கள், பூச்சிகள், மண் அல்லது வானிலை பற்றி கேளுங்கள்...",
    speechActive: "குரல் பதிவு செய்யப்படுகிறது...",
    speechInactive: "பேச மைக் தட்டவும்",
    btnSend: "கேள்",
    irrigationPestScheduler: "நீர் பாசனம் மற்றும் பூச்சி மேலாண்மை நினைவூட்டல்",
    nextIrrigation: "அடுத்த திட்டமிடப்பட்ட பாசனம்",
    pestControl: "பூச்சி மேலாண்மை ஆலோசகர்",
    selectCrop: "பயிரைத் தேர்ந்தெடுக்கவும்",
    selectSymptoms: "அறிகுறிகளைத் தேர்ந்தெடுக்கவும்",
    recommendTreatment: "நோயறிதல் & சிகிச்சை தேடுக",
    pestDiagnosis: "நோயறிதல் முடிவு",
    recommendedPesticide: "பரிந்துரைக்கப்பட்ட பூச்சிக்கொல்லி / தீர்வு",
    safetyInstruction: "பாதுகாப்பு வழிமுறைகள்",
    addReminder: "நினைவூட்டலை திட்டமிடுங்கள்",
    days: "நாட்கள்",
    hours: "மணிநேரம்",
    alertRain: "பாசனம் ரத்து செய்யப்பட்டது: அதிக மழை எதிர்பார்க்கப்படுகிறது!",
    alertIrrigate: "பாசனம் தேவை: மண்ணின் ஈரப்பதம் மிகக் குறைவாக உள்ளது.",
    alertNormal: "ஈரப்பதம் சீராக உள்ளது. அடுத்த பாசனம் 18 மணிநேரத்தில்.",
    mandiUnit: "/ குவிண்டால்",
    currency: "₹"
  },
  te: {
    title: "కృషిగురు",
    subtitle: "స్మార్ట్ రైతు డాష్‌బోర్డ్",
    soilAnalyzer: "నేల ఆరోగ్య విశ్లేషణ",
    nitrogen: "నత్రజని (N)",
    phosphorus: "భాస్వరం (P)",
    potassium: "పొటాషియం (K)",
    phLevel: "నేల pH స్థాయి",
    moisture: "నేల తేమ శాతం",
    soilType: "నేల రకం",
    location: "వ్యవసాయ ప్రాంతం",
    sand: "ఇసుక నేల",
    clay: "నల్ల రేగడి నేల",
    loam: "ఎర్ర నేల (దుంప)",
    silt: "ఒండ్రు నేల",
    peat: "పీట్ నేల",
    chalk: "సున్నపు నేల",
    analyzeBtn: "నేలను విశ్లేషించండి & వాతావరణం పొందండి",
    climateCenter: "వాతావరణం & క్లైమేట్ ఇంటెలిజెన్స్",
    temperature: "ఉష్ణోగ్రత",
    humidity: "తేమ",
    windSpeed: "గాలి వేగం",
    rainChance: "వర్ష సూచన",
    currentConditions: "ప్రస్తుత వాతావరణం",
    weeklyForecast: "7 రోజుల వ్యవసాయ సూచన",
    recommendations: "లాభదాయకమైన పంటల సిఫార్సులు",
    cropName: "పంట పేరు",
    suitability: "అనుకూలత స్కోర్",
    marketPrice: "ప్రస్తుత మార్కెట్ ధర",
    expectedProfit: "అంచనా వేసిన లాభం",
    growthPeriod: "పంట కాలం",
    profitTip: "నిజ సమయ స్థానిక మార్కెట్ ధరల ఆధారంగా లాభం గరిష్టీకరించబడింది.",
    assistantTitle: "కృషి సహాయక్ (వాయిస్ అసిస్టెంట్)",
    assistantGreeting: "నమస్కారం! నేను మీ కృషి సహాయక్. మాట్లాడటానికి మైక్ క్లిక్ చేయండి లేదా మీ ప్రశ్నను టైప్ చేయండి. నేల నాణ్యత, తెగుళ్ల నివారణ, మార్కెట్ ధరలు లేదా నీటి పారుదల గురించి నేను మీకు సహాయం చేస్తాను.",
    placeholder: "పంటలు, తెగుళ్ళు, నేల లేదా వాతావరణం గురించి అడగండి...",
    speechActive: "మీ వాయిస్ వినబడుతోంది...",
    speechInactive: "మాట్లాడటానికి మైక్ క్లిక్ చేయండి",
    btnSend: "అడగండి",
    irrigationPestScheduler: "నీటి పారుదల & తెగుళ్ల అలర్ట్ షెడ్యూలర్",
    nextIrrigation: "తదుపరి నీటి పారుదల",
    pestControl: "తెగుళ్ళ నివారణ సలహాదారు",
    selectCrop: "పంటను ఎంచుకోండి",
    selectSymptoms: "లక్షణాలను ఎంచుకోండి",
    recommendTreatment: "రోగనిర్ధారణ & చికిత్స కనుగొనండి",
    pestDiagnosis: "రోగనిర్ధారణ ఫలితం",
    recommendedPesticide: "సిఫార్సు చేసిన పురుగుమందు / చికిత్స",
    safetyInstruction: "భద్రతా సూచనలు",
    addReminder: "స్ప్రే రిమైండర్ జోడించండి",
    days: "రోజులు",
    hours: "గంటలు",
    alertRain: "నీటి పారుదల వాయిదా: భారీ వర్ష సూచన ఉంది!",
    alertIrrigate: "నీరు పెట్టడం అవసరం: నేలలో తేమ చాలా తక్కువగా ఉంది.",
    alertNormal: "తేమ సాధారణంగా ఉంది. తదుపరి నీరు 18 గంటలలో.",
    mandiUnit: "/ క్వింటాల్",
    currency: "₹"
  },
  bn: {
    title: "কৃষিগুরু",
    subtitle: "স্মার্ট কৃষক ড্যাশবোর্ড",
    soilAnalyzer: "মৃত্তিকা স্বাস্থ্য বিশ্লেষক",
    nitrogen: "নাইট্রোজেন (N)",
    phosphorus: "ফসফরাস (P)",
    potassium: "পটাশিয়াম (K)",
    phLevel: "মাটির পিএইচ (pH) স্তর",
    moisture: "মাটির আর্দ্রতা",
    soilType: "মাটির ধরন",
    location: "কৃষি অঞ্চল",
    sand: "বেলে মাটি",
    clay: "এঁটেল মাটি",
    loam: "দোআঁশ মাটি",
    silt: "পলি মাটি",
    peat: "পিট মাটি",
    chalk: "চুনযুক্ত মাটি",
    analyzeBtn: "মাটি বিশ্লেষণ এবং আবহাওয়া জানুন",
    climateCenter: "জলবায়ু ও আবহাওয়া তথ্য",
    temperature: "তাপমাত্রা",
    humidity: "আর্দ্রতা",
    windSpeed: "বাতাসের গতিবেগ",
    rainChance: "বৃষ্টির সম্ভাবনা",
    currentConditions: "বর্তমান পরিস্থিতি",
    weeklyForecast: "৭-দিনের কৃষি পূর্বাভাস",
    recommendations: "সর্বোচ্চ লাভজনক ফসল সুপারিশ",
    cropName: "ফসলের নাম",
    suitability: "উপযুক্ততা স্কোর",
    marketPrice: "বর্তমান বাজার দর",
    expectedProfit: "আনুমানিক লাভ",
    growthPeriod: "ফসলের সময়কাল",
    profitTip: "স্থানীয় মন্ডির বাজার মূল্যের ভিত্তিতে লাভ সর্বাধিক করা হয়েছে।",
    assistantTitle: "কৃষি সহায়ক (ভয়েস অ্যাসিস্ট্যান্ট)",
    assistantGreeting: "নমস্কার! আমি আপনার কৃষি সহায়ক। কথা বলার জন্য মাইক টিপুন, অথবা আপনার প্রশ্নটি লিখুন। আমি মাটির মান উন্নত করা, পোকা দমন, বাজারের দর বা সেচের সময়সূচী ঠিক করতে সাহায্য করতে পারি।",
    placeholder: "ফসল, পোকা, মাটি বা আবহাওয়া সম্পর্কে যেকোনো কিছু জিজ্ঞাসা করুন...",
    speechActive: "আপনার কথা শোনা হচ্ছে...",
    speechInactive: "বলার জন্য মাইক টিপুন",
    btnSend: "জিজ্ঞাসা",
    irrigationPestScheduler: "স্মার্ট সেচ ও কীট দমন অনুস্মারক",
    nextIrrigation: "পরবর্তী নির্ধারিত সেচ",
    pestControl: "কীটপতঙ্গ দমন উপদেষ্টা",
    selectCrop: "ফসল নির্বাচন করুন",
    selectSymptoms: "লক্ষণগুলি নির্বাচন করুন",
    recommendTreatment: "রোগ নির্ণয় ও চিকিৎসা খুঁজুন",
    pestDiagnosis: "রোগ নির্ণয় ফলাফল",
    recommendedPesticide: "প্রস্তাবিত কীটনাশক / প্রতিকার",
    safetyInstruction: "নিরাপত্তা নির্দেশাবলী",
    addReminder: "স্প্রে অনুস্মারক যুক্ত করুন",
    days: "দিন",
    hours: "ঘণ্টা",
    alertRain: "সেচ স্থগিত: ভারী বৃষ্টির পূর্বাভাস রয়েছে!",
    alertIrrigate: "সেচ প্রয়োজন: মাটির আর্দ্রতা অত্যন্ত কম।",
    alertNormal: "মাটির আর্দ্রতা স্বাভাবিক। ১৮ ঘণ্টা পর জল দিন।",
    mandiUnit: "/ কুইন্টাল",
    currency: "₹"
  }
};
